
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adam
 */
public class ResolveSVNConflicts {

    /**
     * resolves problems in SVN
     *
     * @param args the path to the conflicting CASUALApp files
     */
    public static void main(String[] args){
        String path = args[0];
        File folder = new File(path);
        int casualAppCount = 0;
        int highestBuildNumber = 0;
        int highestSVNNumber = 0;
        Properties casualAppProp = new Properties();
        String casAppPath = path + "CASUALApp.properties";
        try {
            casualAppProp.load(new FileInputStream(casAppPath));
        } catch (IOException ex) {
            return;
        }

        for (String f : folder.list()) {
            if (f.contains("CASUALApp.properties")) {
                casualAppCount++;
                Properties prop = new Properties();
                try {
                    System.out.println("loading: "+ path + "/" + f);
                    try (FileInputStream fis = new FileInputStream(path + "/" + f)) {
                        prop.load(fis);
                    }
                    String buildStr = prop.getProperty("Application.buildnumber");
                    String svnStr = prop.getProperty("Application.revision");
                    System.out.println("Checking: build=" + buildStr + " revision=" + svnStr);
                    highestBuildNumber = testValueForHigher(highestBuildNumber, prop, "Application.buildnumber");
                    highestSVNNumber = testValueForHigher(highestSVNNumber, prop, "Application.revision");
                    
                } catch (FileNotFoundException ex) {
                    return;
                } catch (IOException ex) {
                    return;
                }

            }
        }
        if (casualAppCount > 1) {
            System.out.println("there are multiple metas.  merging and cleaning.\nStoring the true " + casAppPath);
            if (highestBuildNumber > 1) {
                casualAppProp.setProperty("Application.buildnumber", Integer.toString(highestBuildNumber));
                System.out.println("new Application.buildnumber=" + casualAppProp.getProperty("Application.buildnumber"));
            }
            if (highestSVNNumber > 1) {
                casualAppProp.setProperty("Application.revision", Integer.toString(highestSVNNumber));
                System.out.println("new Application.revision=" + casualAppProp.getProperty("Application.revision"));
            }
            casualAppProp.remove("");
            casualAppProp.remove("<<<<<<<");
            casualAppProp.remove(">>>>>>>");


            /*try {
             } catch (IOException ex) {
             return;
             }*/
            for (String f : folder.list()) {
                if (f.contains("CASUALApp.properties")) {
                    if (!(new File(f).getName().equals("CASUALApp.properties"))) {
                        File del= new File(path + f);
                        System.out.println("removing: "+ path + f +" "+ del.delete());
                    } else {
                        System.out.println("storing: " +path +  f);
                        try {
                            casualAppProp.store(new FileOutputStream(casAppPath), "Properties file generated by BuildTasks/ResolveSVNConflics during build time.\nIf you are having problems with this file, ensure that there are no SVN conflicts prior to setting values.");
                        } catch (FileNotFoundException ex) {
                            return;
                        } catch (IOException ex) {
                            return;
                        }

                    }
                }
            }
        }
    }

    private static int testValueForHigher(int highNumber, Properties prop, String property) {
        String testValue = prop.getProperty(property).replace(",", "");

        if (Integer.parseInt(testValue) > 0) {
            int testInt = Integer.parseInt(testValue);
            if (testInt > highNumber) {
                return testInt;
            }
        }
        return highNumber;
    }
}
