/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CASCADEGUI.ScriptTimeline;


import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author loganludington
 */
public class ScriptTimelineWindow extends javax.swing.JFrame {

    ArrayList<Command> commandArrayList = new ArrayList<Command>();
    DefaultMutableTreeNode commandList = new DefaultMutableTreeNode("Command List Types");
    DefaultMutableTreeNode commands = new DefaultMutableTreeNode("Commands");
    DefaultMutableTreeNode conditionals = new DefaultMutableTreeNode("Conditionals");
    DefaultMutableTreeNode prompts = new DefaultMutableTreeNode("Prompts");
    DefaultMutableTreeNode statics = new DefaultMutableTreeNode("Statics");
    DefaultMutableTreeNode controls = new DefaultMutableTreeNode("Controls");

    /**
     * Creates new form CASCADEGUIScriptTimeline
     */
    public ScriptTimelineWindow() {
        initComponents();
        commandList.add(commands);
        commandList.add(conditionals);
        commandList.add(prompts);
        commandList.add(statics);
        commandList.add(controls);
        makeCommandList();
        blankOutJLabels();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree(commandList);
        jPanel5 = new javax.swing.JPanel();
        commandNameTitle = new javax.swing.JLabel();
        commandTypeTitle = new javax.swing.JLabel();
        commandSyntaxTitle = new javax.swing.JLabel();
        commandDescriptionTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commandDescriptionTextArea = new javax.swing.JTextArea();
        commandNameLabel = new javax.swing.JLabel();
        commandTypeLabel = new javax.swing.JLabel();
        commandSyntaxLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("CASCADEGUI/resources/CGSTBundle"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ScriptTimelineWindow.jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ScriptTimelineWindow.jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTree1.setName("jTree1"); // NOI18N
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jTree1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ScriptTimelineWindow.jPanel5.border.title"))); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N

        commandNameTitle.setText(bundle.getString("ScriptTimelineWindow.commandNameTitle.text")); // NOI18N
        commandNameTitle.setName("commandNameTitle"); // NOI18N

        commandTypeTitle.setText(bundle.getString("ScriptTimelineWindow.commandTypeTitle.text")); // NOI18N
        commandTypeTitle.setName("commandTypeTitle"); // NOI18N

        commandSyntaxTitle.setText(bundle.getString("ScriptTimelineWindow.commandSyntaxTitle.text")); // NOI18N
        commandSyntaxTitle.setName("commandSyntaxTitle"); // NOI18N

        commandDescriptionTitle.setText(bundle.getString("ScriptTimelineWindow.commandDescriptionTitle.text")); // NOI18N
        commandDescriptionTitle.setName("commandDescriptionTitle"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        commandDescriptionTextArea.setColumns(20);
        commandDescriptionTextArea.setLineWrap(true);
        commandDescriptionTextArea.setRows(5);
        commandDescriptionTextArea.setWrapStyleWord(true);
        commandDescriptionTextArea.setName("commandDescriptionTextArea"); // NOI18N
        jScrollPane2.setViewportView(commandDescriptionTextArea);

        commandNameLabel.setText(bundle.getString("ScriptTimelineWindow.commandNameLabel.text")); // NOI18N
        commandNameLabel.setName("commandNameLabel"); // NOI18N

        commandTypeLabel.setText(bundle.getString("ScriptTimelineWindow.commandTypeLabel.text")); // NOI18N
        commandTypeLabel.setName("commandTypeLabel"); // NOI18N

        commandSyntaxLabel.setText(bundle.getString("ScriptTimelineWindow.commandSyntaxLabel.text")); // NOI18N
        commandSyntaxLabel.setName("commandSyntaxLabel"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(commandNameTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commandNameLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(commandTypeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commandTypeLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(commandSyntaxTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commandSyntaxLabel))
                    .addComponent(commandDescriptionTitle))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commandNameTitle)
                    .addComponent(commandNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commandTypeTitle)
                    .addComponent(commandTypeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commandSyntaxTitle)
                    .addComponent(commandSyntaxLabel))
                .addGap(18, 18, 18)
                .addComponent(commandDescriptionTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ScriptTimelineWindow.jPanel3.border.title"))); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ScriptTimelineWindow.jPanel4.border.title"))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        if (commandArrayList.contains(jTree1.getSelectionPath().getLastPathComponent().toString())) {
            System.out.println("test");
        }
    }//GEN-LAST:event_jTree1ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("System".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScriptTimelineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScriptTimelineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScriptTimelineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScriptTimelineWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScriptTimelineWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commandDescriptionTextArea;
    private javax.swing.JLabel commandDescriptionTitle;
    private javax.swing.JLabel commandNameLabel;
    private javax.swing.JLabel commandNameTitle;
    private javax.swing.JLabel commandSyntaxLabel;
    private javax.swing.JLabel commandSyntaxTitle;
    private javax.swing.JLabel commandTypeLabel;
    private javax.swing.JLabel commandTypeTitle;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    public final void makeCommandList() {
        Properties prop = new Properties();
        try {
            prop.load(CASCADEGUI.CASCADEGUI.class.getClassLoader().getResourceAsStream("CASCADEGUI/resources/Commands.properties"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ScriptTimelineWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ScriptTimelineWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String s : prop.stringPropertyNames()) {
            if (s.contains(".Name")) {
                commandArrayList.add(new Command(prop.getProperty(s), prop));
            }

        }


        for (Command c : commandArrayList) {
            if (c.equals("Control")) {
                controls.add(new DefaultMutableTreeNode(c));
            } else if (c.equals("Command")) {
                commands.add(new DefaultMutableTreeNode(c));
            } else if (c.equals("Static")) {
                statics.add(new DefaultMutableTreeNode(c));
            } else if (c.equals("Conditional")) {
                conditionals.add(new DefaultMutableTreeNode(c));
            } else if (c.equals("Prompt")) {
                prompts.add(new DefaultMutableTreeNode(c));


            }
        }
    }

    private void blankOutJLabels() {
        this.commandNameLabel.setText("");
        this.commandSyntaxLabel.setText("");
        this.commandTypeLabel.setText("");
        this.commandDescriptionTextArea.setText("");
    }

    public class Command {

        public String name = "";
        public String type = "";
        public String script = "";
        public String syntax = "";
        public String description = "";

        public Command(String name, Properties prop) {
            this.name = name.trim();
            this.type = prop.getProperty("Commands." + name + ".Type");
            this.script = prop.getProperty("Commands." + name + ".Script");
            this.syntax = prop.getProperty("Commands." + name + ".Syntax");
            this.description = prop.getProperty("Commands." + name + ".Description");
        }

        public Command() {
        }

        @Override
        public String toString() {
            return name;
        }
    }
}
