/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CASPACcreator.CASPACcreatorGUI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.bind.DatatypeConverter;
import javax.swing.ImageIcon;

/**
 *
 * @author loganludington
 */
public class mainWindow extends javax.swing.JFrame {

    private static final String trashIcon ="89504e470d0a1a0a0000000d4948445200000010000000100804000000b5fa37ea000000097048597300000b1300000b1301009a9c18000003186943435050686f746f73686f70204943432070726f66696c65000078da6360609ee0e8e2e4ca24c0c050505452e41ee418191119a5c07e9e818d819981818181812131b9b8c03120c087818181212f3f2f9501153032307cbbc6c0c8c0c0c07059d7d1c5c9958134c09a5c5054c2c0c070808181c12825b538998181e10b0303437a794941090303630c03038348527641090303630103038348764890330303630b0303134f496a450903030383737e416551667a468982a1a5a5a582634a7e52aa42706571496a6eb182675e727e51417e5162496a0a030303d40e060606065e97fc1205f7c4cc3c05230355062a8388c82805080b113e083104482e2d2a83072503830083028301830343004322433dc30286a30c6f18c5195d184b195730de6312630a629ac07481599839927921f31b164b960e965bac7aacadacf7d82cd9a6b17d630f67dfcda1c4d1c5f1853391f3029723d7166e4dee053c523c5379857827f109f34de397e15f2ca023b043d055f08a50aad00fe15e111591bda2e1a25fc426891b895f91a89094933c26952f2d2d7d42a64c565df6965c9fbc8bfc1f85ad8a854a7a4a6f95d7aa14a89aa8fe543ba8dea511aaa9a4f941eb80f6249d545d2b3d41bd57fa470c1618d61ac518db9ac89b329bbe34bb60bed36289e504ab3aeb5c9b38db403b577b6b0763471d2735672517055779370577650f754f5d2f136f1b1f77df60bf04fffc80fac089414b8377855c0c7d19ce142117691515115d113333764fdc8304b644dda4b0e4869435a937d339322c3233b3e6665fcc65cfb3cfaf28d854f8ae58bb24ab7455d99b0afdca92aa5d358cb55e7553eb1f36ea35d5349f6d956b2b6c3fda29dd55d47dba57b5afb1ffee449b49b327ff9d1a3fedf00c8d99fdb3becf49987b7abef982a58b4416b72ef9b62c73f9bd9521ab4eaf7159bb6fbde5866d9b4c366fd96ab26dfb0eab9dfb77bbee39bb2f6cff838339877e1e693f267e7cc549eb53e7ce249ffd757ed245ed4b47af245efd777dce4d9b5b77efd4df53be7fe261de63b127fb9f65be107979f075fe5bf977173e347d32fdfceaeb82efe13f057e9dfad3facff1ff7f000d000f34fa96f15d000000206348524d00007a25000080830000f9ff000080e9000075300000ea6000003a980000176f925fc546000000f04944415478da8cd1ab4a04601005e0efdf5d2fec066f08168b884f2098c46235992c16ad169fc06031984c3e80c505ab60315a4410149382c9455804415c51770cff5e14f1326518ce99cb3993c2ef51ca29e5346b59b2e73897819427a4255b1a1ed58561032a36ed467409fb46dd49b909837a6cc761973061cdb81b434a6a26d5edb88cbc2704b3c28107278ebcaa0a0b196b13e6dd9b726dd5a29a31b7163356d03eb847c5bbb25ea1aca8a5bff04972122dbd49c79ec21f3efd9f10684a9a026fdf57f4e359494353f2a2a4afd31a8269e15cc3852b4fce84b98cb59d64dd8a53238aeecca8daf8f2ac9fe363006b5d542ebf959c0a0000000049454e44ae426082";
    private mainWindowController mwc = null;
    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        mwc = new mainWindowController(this);
        //this.jList1.setModel(mwc.getListModel());
        
    }

    public mainWindow(mainWindowController mwc) {
        initComponents();
        this.mwc = mwc;
        this.setLocationRelativeTo(null);
        //this.jList1.setModel(this.mwc.getListModel());
        this.outputFile.setText(mwc.getOutputFile());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BannerPicOrText = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        outputFIle = new javax.swing.JPanel();
        outputFile = new javax.swing.JTextField();
        makeCASPAC = new javax.swing.JButton();
        workArea = new javax.swing.JTabbedPane();
        scriptGroup = new javax.swing.JTabbedPane();
        script = new javax.swing.JPanel();
        scriptText = new javax.swing.JScrollPane();
        scriptWorkArea = new javax.swing.JTextArea();
        txtfile = new javax.swing.JPanel();
        descriptionScrollpane = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        zip = new javax.swing.JPanel();
        zipList = new javax.swing.JScrollPane();
        resourcesForScript = new javax.swing.JList();
        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        meta = new javax.swing.JPanel();
        minSVNversion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        scriptRevision = new javax.swing.JTextField();
        uniqueID = new javax.swing.JTextField();
        supportURL = new javax.swing.JTextField();
        updateMessage = new javax.swing.JTextField();
        killswitchMessage = new javax.swing.JTextField();
        overviewScrollPane = new javax.swing.JScrollPane();
        overviewWorkArea = new javax.swing.JTextArea();
        buildPropertiesPanel = new javax.swing.JPanel();
        developerName = new javax.swing.JTextField();
        donationPanel = new javax.swing.JPanel();
        donateLink = new javax.swing.JTextField();
        donateText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        windowText = new javax.swing.JTextField();
        buttonText = new javax.swing.JTextField();
        alwaysEnableControls = new javax.swing.JCheckBox();
        audioEnabled = new javax.swing.JCheckBox();
        useBannerText = new javax.swing.JRadioButton();
        useBannerPic = new javax.swing.JRadioButton();
        bannerPic = new javax.swing.JTextField();
        bannerText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("CASPACcreator/CASPACcreatorGUI/Bundle"); // NOI18N
        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mainWindow.mainPanel.border.title"))); // NOI18N
        mainPanel.setName("mainPanel"); // NOI18N

        outputFIle.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mainWindow.outputFIle.border.title"))); // NOI18N
        outputFIle.setName("outputFIle"); // NOI18N

        outputFile.setText(System.getProperty("user.dir"));
        outputFile.setName("outputFile"); // NOI18N
        outputFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileActionPerformed(evt);
            }
        });

        makeCASPAC.setText(bundle.getString("mainWindow.makeCASPAC.text")); // NOI18N
        makeCASPAC.setName("makeCASPAC"); // NOI18N
        makeCASPAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeCASPACActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout outputFIleLayout = new javax.swing.GroupLayout(outputFIle);
        outputFIle.setLayout(outputFIleLayout);
        outputFIleLayout.setHorizontalGroup(
            outputFIleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputFIleLayout.createSequentialGroup()
                .addComponent(outputFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makeCASPAC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        outputFIleLayout.setVerticalGroup(
            outputFIleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(makeCASPAC)
            .addComponent(outputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        workArea.setName(""); // NOI18N

        scriptGroup.setName("scriptGroup"); // NOI18N

        script.setName("script"); // NOI18N

        scriptText.setName("scriptText"); // NOI18N

        scriptWorkArea.setColumns(20);
        scriptWorkArea.setRows(5);
        scriptWorkArea.setText(bundle.getString("mainWindow.scriptWorkArea.text")); // NOI18N
        scriptWorkArea.setName("scriptWorkArea"); // NOI18N
        scriptText.setViewportView(scriptWorkArea);

        javax.swing.GroupLayout scriptLayout = new javax.swing.GroupLayout(script);
        script.setLayout(scriptLayout);
        scriptLayout.setHorizontalGroup(
            scriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scriptText, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        scriptLayout.setVerticalGroup(
            scriptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scriptText, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        scriptGroup.addTab(bundle.getString("mainWindow.script.TabConstraints.tabTitle"), script); // NOI18N

        txtfile.setName("txtfile"); // NOI18N

        descriptionScrollpane.setName("descriptionScrollpane"); // NOI18N

        description.setColumns(20);
        description.setLineWrap(true);
        description.setRows(5);
        description.setText(bundle.getString("mainWindow.description.text")); // NOI18N
        description.setWrapStyleWord(true);
        description.setName("description"); // NOI18N
        descriptionScrollpane.setViewportView(description);

        javax.swing.GroupLayout txtfileLayout = new javax.swing.GroupLayout(txtfile);
        txtfile.setLayout(txtfileLayout);
        txtfileLayout.setHorizontalGroup(
            txtfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        txtfileLayout.setVerticalGroup(
            txtfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(descriptionScrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        scriptGroup.addTab(bundle.getString("mainWindow.txtfile.TabConstraints.tabTitle"), txtfile); // NOI18N

        zip.setName("zip"); // NOI18N

        zipList.setName("zipList"); // NOI18N

        resourcesForScript.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        resourcesForScript.setName("resourcesForScript"); // NOI18N
        zipList.setViewportView(resourcesForScript);

        add.setIcon(new ImageIcon(DatatypeConverter.parseHexBinary(trashIcon)));
        add.setText(bundle.getString("mainWindow.add.text")); // NOI18N
        add.setName("add"); // NOI18N
        add.setPreferredSize(new java.awt.Dimension(35, 30));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        remove.setText(bundle.getString("mainWindow.remove.text")); // NOI18N
        remove.setName("remove"); // NOI18N
        remove.setPreferredSize(new java.awt.Dimension(35, 30));
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zipLayout = new javax.swing.GroupLayout(zip);
        zip.setLayout(zipLayout);
        zipLayout.setHorizontalGroup(
            zipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zipList)
            .addGroup(zipLayout.createSequentialGroup()
                .addGap(0, 566, Short.MAX_VALUE)
                .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        zipLayout.setVerticalGroup(
            zipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zipLayout.createSequentialGroup()
                .addComponent(zipList, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(zipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        scriptGroup.addTab(bundle.getString("mainWindow.zip.TabConstraints.tabTitle"), zip); // NOI18N

        meta.setName("meta"); // NOI18N

        minSVNversion.setText(bundle.getString("mainWindow.minSVNversion.text")); // NOI18N
        minSVNversion.setName("minSVNversion"); // NOI18N

        jLabel1.setText(bundle.getString("mainWindow.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(bundle.getString("mainWindow.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(bundle.getString("mainWindow.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(bundle.getString("mainWindow.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(bundle.getString("mainWindow.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(bundle.getString("mainWindow.jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        scriptRevision.setText(bundle.getString("mainWindow.scriptRevision.text")); // NOI18N
        scriptRevision.setName("scriptRevision"); // NOI18N
        scriptRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scriptRevisionActionPerformed(evt);
            }
        });

        uniqueID.setText(bundle.getString("mainWindow.uniqueID.text")); // NOI18N
        uniqueID.setName("uniqueID"); // NOI18N

        supportURL.setText(bundle.getString("mainWindow.supportURL.text")); // NOI18N
        supportURL.setName("supportURL"); // NOI18N

        updateMessage.setText(bundle.getString("mainWindow.updateMessage.text")); // NOI18N
        updateMessage.setName("updateMessage"); // NOI18N

        killswitchMessage.setText(bundle.getString("mainWindow.killswitchMessage.text")); // NOI18N
        killswitchMessage.setName("killswitchMessage"); // NOI18N

        javax.swing.GroupLayout metaLayout = new javax.swing.GroupLayout(meta);
        meta.setLayout(metaLayout);
        metaLayout.setHorizontalGroup(
            metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(metaLayout.createSequentialGroup()
                        .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateMessage)
                            .addComponent(killswitchMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)))
                    .addGroup(metaLayout.createSequentialGroup()
                        .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(metaLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(supportURL))
                            .addGroup(metaLayout.createSequentialGroup()
                                .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(metaLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(59, 59, 59)
                                        .addComponent(uniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, metaLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(21, 21, 21)
                                            .addComponent(scriptRevision))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, metaLayout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(minSVNversion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        metaLayout.setVerticalGroup(
            metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minSVNversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scriptRevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(supportURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(updateMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(metaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(killswitchMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        scriptGroup.addTab(bundle.getString("mainWindow.meta.TabConstraints.tabTitle"), meta); // NOI18N

        workArea.addTab(bundle.getString("mainWindow.scriptGroup.TabConstraints.tabTitle"), scriptGroup); // NOI18N

        overviewScrollPane.setName("overviewScrollPane"); // NOI18N

        overviewWorkArea.setColumns(20);
        overviewWorkArea.setLineWrap(true);
        overviewWorkArea.setRows(5);
        overviewWorkArea.setText(bundle.getString("mainWindow.overviewWorkArea.text")); // NOI18N
        overviewWorkArea.setWrapStyleWord(true);
        overviewWorkArea.setName("overviewWorkArea"); // NOI18N
        overviewScrollPane.setViewportView(overviewWorkArea);

        workArea.addTab(bundle.getString("mainWindow.overviewScrollPane.TabConstraints.tabTitle"), overviewScrollPane); // NOI18N

        buildPropertiesPanel.setName("buildPropertiesPanel"); // NOI18N

        developerName.setText(bundle.getString("mainWindow.developerName.text")); // NOI18N
        developerName.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mainWindow.developerName.border.title"))); // NOI18N
        developerName.setName("developerName"); // NOI18N

        donationPanel.setName("donationPanel"); // NOI18N

        donateLink.setText(bundle.getString("mainWindow.donateLink.text")); // NOI18N
        donateLink.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mainWindow.donateLink.border.title"))); // NOI18N
        donateLink.setName("donateLink"); // NOI18N

        donateText.setText(bundle.getString("mainWindow.donateText.text")); // NOI18N
        donateText.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mainWindow.donateText.border.title"))); // NOI18N
        donateText.setName("donateText"); // NOI18N

        javax.swing.GroupLayout donationPanelLayout = new javax.swing.GroupLayout(donationPanel);
        donationPanel.setLayout(donationPanelLayout);
        donationPanelLayout.setHorizontalGroup(
            donationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donationPanelLayout.createSequentialGroup()
                .addComponent(donateText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donateLink))
        );
        donationPanelLayout.setVerticalGroup(
            donationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(donateText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(donateLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setName("jPanel4"); // NOI18N

        windowText.setText(bundle.getString("mainWindow.windowText.text")); // NOI18N
        windowText.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mainWindow.windowText.border.title"))); // NOI18N
        windowText.setName("windowText"); // NOI18N

        buttonText.setText(bundle.getString("mainWindow.buttonText.text")); // NOI18N
        buttonText.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mainWindow.buttonText.border.title"))); // NOI18N
        buttonText.setName("buttonText"); // NOI18N

        alwaysEnableControls.setText(bundle.getString("mainWindow.alwaysEnableControls.text")); // NOI18N
        alwaysEnableControls.setName("alwaysEnableControls"); // NOI18N

        audioEnabled.setSelected(true);
        audioEnabled.setText(bundle.getString("mainWindow.audioEnabled.text")); // NOI18N
        audioEnabled.setName("audioEnabled"); // NOI18N

        BannerPicOrText.add(useBannerText);
        useBannerText.setSelected(true);
        useBannerText.setText(bundle.getString("mainWindow.useBannerText.text")); // NOI18N
        useBannerText.setName("useBannerText"); // NOI18N

        BannerPicOrText.add(useBannerPic);
        useBannerPic.setText(bundle.getString("mainWindow.useBannerPic.text")); // NOI18N
        useBannerPic.setName("useBannerPic"); // NOI18N

        bannerPic.setText(bundle.getString("mainWindow.bannerPic.text")); // NOI18N
        bannerPic.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mainWindow.bannerPic.border.title"))); // NOI18N
        bannerPic.setName("bannerPic"); // NOI18N

        bannerText.setText(bundle.getString("mainWindow.bannerText.text")); // NOI18N
        bannerText.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("mainWindow.bannerText.border.title"))); // NOI18N
        bannerText.setName("bannerText"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(windowText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alwaysEnableControls)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioEnabled))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useBannerPic)
                            .addComponent(useBannerText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bannerPic)
                            .addComponent(bannerText, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(windowText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(alwaysEnableControls)
                        .addComponent(audioEnabled)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bannerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useBannerText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bannerPic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useBannerPic))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout buildPropertiesPanelLayout = new javax.swing.GroupLayout(buildPropertiesPanel);
        buildPropertiesPanel.setLayout(buildPropertiesPanelLayout);
        buildPropertiesPanelLayout.setHorizontalGroup(
            buildPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buildPropertiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buildPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(developerName)
                    .addComponent(donationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buildPropertiesPanelLayout.setVerticalGroup(
            buildPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buildPropertiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(developerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        workArea.addTab(bundle.getString("mainWindow.buildPropertiesPanel.TabConstraints.tabTitle"), buildPropertiesPanel); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workArea, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(outputFIle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(workArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputFIle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makeCASPACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeCASPACActionPerformed
        try {
            // TODO add your handling code here:
            mwc.zipFiles(outputFile.getText());
        } catch (IOException ex) {
            Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_makeCASPACActionPerformed

    private void outputFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputFileActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void scriptRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scriptRevisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scriptRevisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BannerPicOrText;
    private javax.swing.JButton add;
    private javax.swing.JCheckBox alwaysEnableControls;
    private javax.swing.JCheckBox audioEnabled;
    private javax.swing.JTextField bannerPic;
    private javax.swing.JTextField bannerText;
    private javax.swing.JPanel buildPropertiesPanel;
    private javax.swing.JTextField buttonText;
    private javax.swing.JTextArea description;
    private javax.swing.JScrollPane descriptionScrollpane;
    private javax.swing.JTextField developerName;
    private javax.swing.JTextField donateLink;
    private javax.swing.JTextField donateText;
    private javax.swing.JPanel donationPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField killswitchMessage;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton makeCASPAC;
    private javax.swing.JPanel meta;
    private javax.swing.JTextField minSVNversion;
    private javax.swing.JPanel outputFIle;
    private javax.swing.JTextField outputFile;
    private javax.swing.JScrollPane overviewScrollPane;
    private javax.swing.JTextArea overviewWorkArea;
    private javax.swing.JButton remove;
    private javax.swing.JList resourcesForScript;
    private javax.swing.JPanel script;
    private javax.swing.JTabbedPane scriptGroup;
    private javax.swing.JTextField scriptRevision;
    private javax.swing.JScrollPane scriptText;
    private javax.swing.JTextArea scriptWorkArea;
    private javax.swing.JTextField supportURL;
    private javax.swing.JPanel txtfile;
    private javax.swing.JTextField uniqueID;
    private javax.swing.JTextField updateMessage;
    private javax.swing.JRadioButton useBannerPic;
    private javax.swing.JRadioButton useBannerText;
    private javax.swing.JTextField windowText;
    private javax.swing.JTabbedPane workArea;
    private javax.swing.JPanel zip;
    private javax.swing.JScrollPane zipList;
    // End of variables declaration//GEN-END:variables


}
